server {
    listen 8080;

    # Route backend Java API traffic
    location /api/ {
        proxy_pass http://backend-service:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route all other traffic to the React Client dev server
    location / {
        proxy_pass http://client:5173; # Default Vite port
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
